### ISSUE TITLE
Getting started on Mac

### ISSUE THREAD

**Issue by darzu** [Ptival/PeaCoq#1]
Hi!

I'm really new to Coq, and pretty new to unix. I'm trying to get PeaCoq running on OS X Yosemite. While installing PeaCoq, I encountered the following issues. I figured they may be useful to others and/or worth putting into a doc:
- I'm not sure what "cabal" is, but some Googling seems to suggest I should install the Haskell platform: https://www.haskell.org/platform/mac.html. So that's what I did and it seemed to work.
- When I run setup.sh, I get `line 8: wget: command not found`, so I blindly ran `brew install wget` (brew is my package manager) and I believe that worked.
- After I ran `cabal install` I ran `peacoq -p 4321` and got the error: `bash: peacoq: command not found`. I'm not sure what to do now..

That's all for now, I'm looking forward to using your tool!

P.S. In case it means anything to you: I'm in Zach's 505 class this Winter.

**Comment by Ptival** [comment]
Hello, yes I forgot to explicitly list the dependencies, I will add a note about it. Thanks! :)

**Comment by darzu** [comment]
Thanks @Ptival . How about for the last bullet point? I'm still confused on how to actually run peacoq..

**Comment by Ptival** [comment]
Oh, you might need to add the cabal binary directory to your PATH environment variable. The path should be `~/.cabal/bin`.

**Comment by darzu** [comment]
Ah thanks, I actually had to add `~/Library/Haskell/bin` to my path.

**Comment by Ptival** [comment]
@Darzu ah yes, sorry, I am not used to Mac environment.
