### ISSUE TITLE
Wrong child displaying when focusing on n-th subgoal

### ISSUE THREAD

**Issue by tune-george** [Ptival/PeaCoq#10]
This happened in [homework 2](http://courses.cs.washington.edu/courses/cse505/15wi/hw02/hw02.v) when trying to prove Lemma step_None_Skip. Apparently it's a bug.

Server revision: d07b3a65beb76dd8d7cce3b1fbe58f2eef455df9
Client revision: 63caf0106e6fc4022f038b750b27dafa47584526

![image](https://cloud.githubusercontent.com/assets/7853891/6086986/083d731c-adfb-11e4-93b3-78cdd3b54f0c.png)

**Comment by Ptival** [comment]
Yeah, I know about this bug, though I can never reproduce it on my machine.

What you can do to avoid this bug is to process your subgoals in order. In fact I should probably disable the ability to work through them in different order until I figure out a safer way to do so...
