### ISSUE TITLE
Automatically inserting `Qed` and going out of proof mode is inconvenient

### ISSUE THREAD

**Issue by gasche** [Ptival/PeaCoq#18]
Here was my interaction and why I found it inconvenient.

I thought I could use "replace" to finish a proof but forgot about the "by auto" to say the equality proof was trivial. Because the equality goal is the second one (and I wanted to check it was indeed trivial before going on), I admitted the first goal and indeed discharged the second one with "auto". But then PeaCoq noticed that the proof was done, automatically inserted a `Qed.`. It left me out of the the-bottom-panel-shows-the-goal state, in such a way that it was hard to just go back in where I was (ctrl-alt-p would go back to the very beginning of the proof, I think).

Maybe letting users add `Qed` manually (maybe with a "finished: Qed-ready" action in the proof-tree view that can be selected to insert it for auto-discoverability) would result in a less surprising behavior. (Having support for after-all-goals-are-closed proof-tree-view actions would also come handy for coinductive proof.)

**Comment by Ptival** [comment]
Not relevant anymore.
