### ISSUE TITLE
Error Installing in Debian Weezy

### ISSUE THREAD

**Issue by wtonribeiro** [Ptival/PeaCoq#21]
Dear,

I got an error in installing PeaCoq on Debian Weezy:

cabal install
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: peacoq-0.1 (user goal)
next goal: base (dependency of peacoq-0.1)
rejecting: base-4.5.0.0/installed-40b... (conflict: peacoq => base>=4.8 &&
<4.9)
rejecting: base-4.8.1.0, 4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0,
4.5.1.0, 4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1,
4.2.0.0, 4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint requires
installed instance)
Dependency tree exhaustively searched.

Thanks,
Washington

**Comment by ztatlock** [comment]
I believe this may be caused by an old GHC install.

Please install GHC 7.10.2 (the current version shipped with the Haskell platform) and give it another try.

Good luck!  Please keep us posted on any issues that may come up.

**Comment by wtonribeiro** [comment]
Perfect Zach!

I've used the binary generic package of the haskell platform and everything works!

Best
![peacoq](https://cloud.githubusercontent.com/assets/7083604/10138687/197df884-65d6-11e5-9f96-34e260b9ceb3.png)

**Comment by ztatlock** [comment]
Awesome, glad it worked :)  Keep us posted on any issues you come across and happy hacking!
