### ISSUE TITLE
Docker image fails to build

### ISSUE THREAD

**Issue by emichael** [Ptival/PeaCoq#24]
I get the following error when I try to build the Docker image:

```
cabal: Error: some packages failed to install:
pcre-light-0.4.0.4 failed during the configure step. The exception was:
ExitFailure 1
peacoq-0.1 depends on pcre-light-0.4.0.4 which failed to install.
snap-extras-0.11.0.2 depends on pcre-light-0.4.0.4 which failed to install.
INFO[0585] The command [/bin/sh -c cabal install] returned a non-zero code: 1 
```

**Comment by Ptival** [comment]
Thanks for the patch. Actually, we might also get rid of that pcre dependency thanks to #23.

**Comment by emichael** [comment]
Okay, sounds good. You might try using Docker Hub to store and automatically update the image, both so users don't have to go through the lengthy install and for continuous testing of the build process.

**Comment by ztatlock** [comment]
+1 for Docker Hub

**Comment by Ptival** [comment]
re. Docker Hub, I have been trying to use it to no success this afternoon.

10 minutes after a build job is created, it goes to status error and the entire contents of the build page get deleted.

**Comment by emichael** [comment]
That is really odd. The same thing happened to me, but the build actually succeeded. Maybe they delete logs after successful builds? If yours didn't actually succeed, did you specify the docker file location (`/docker/`) on the Build Settings tab?

**Comment by emichael** [comment]
Okay, on the next build for me apt-get timed out on fetching packages for some reason, and the entire build failed. At least it saved the logs that time, though.

If the automated build feature on Docker Hub is kind of broken, Travis CI might be a better solution. See http://docs.travis-ci.com/user/docker/

**Comment by Ptival** [comment]
I got the Docker Hub started at:
https://hub.docker.com/r/ptival/peacoq/

And a Travis CI started at:
https://travis-ci.org/Ptival/PeaCoq

**Comment by emichael** [comment]
Nice!!

I have no idea why docker hub builds keep failing, but at least if some of them succeed, that will be good enough.

**Comment by Ptival** [comment]
Yeah, I don't have a good Internet here to try the succesful ones but I'll
try and check it they actually work soon.

It would be nice if the broken ones had a log, right now their website is
pretty useless... :(
