### ISSUE TITLE
Mac: failed to run

### ISSUE THREAD

**Issue by corwin-of-amber** [Ptival/PeaCoq#28]
After a fresh build from GitHub clone, running

```
peacoq -p 7000
```

And then navigating to `http://localhost:7000`, the UI appears but then an alert box shows up with the message: "Server did not respond!"

The log contains the error (occurring multiple times):

```
["127.0.0.1"]: an exception escaped to toplevel:
recv: resource vanished (Connection reset by peer)
```

Same behavior using Safari 9, Firefox 44, and Chrome 48.

Attached `.log`, `-access.log`, and `-error.log`: [peacoq-logs.zip](https://github.com/Ptival/PeaCoq/files/131284/peacoq-logs.zip)

**Comment by Ptival** [comment]
I'm a little busy at the moment working on a new version of PeaCoq.

Did you run the setup script? Could you make sure that your ~/.PeaCoqConfig.hs contains a coqtop command, and that this command works in your terminal?

In particular, which Coq version are you running? I believe master is not compatible with 8.5.

**Comment by corwin-of-amber** [comment]
Switching to 8.4 solved this issue; looks like the `-ideslave` flag does not work with 8.5:

```
% coqtop -ideslave
Fatal error: ideslave communication channels not set.
```

Will try the coq8.5 branch too!

**Comment by Ptival** [comment]
Hah, I think you should wait before trying the coq8.5 branch though, the setup script is not up-to-date, and there are still a few moving pieces. But I have hopes of getting everything rolling in the coming weeks!
