### ISSUE TITLE
Basic help: keyboard shortcuts

### ISSUE THREAD

**Issue by darzu** [Ptival/PeaCoq#3]
I'd be nice to have a list of keyboard shortcuts accessible from somewhere within the app or readmes.

**Comment by Ptival** [comment]
Fixed by c302758d0872c92a165c8fdb64b51df383332c3c

**Comment by ztatlock** [comment]
Nice.

On Tuesday, January 27, 2015, Valentin Robert notifications@github.com
wrote:

> Closed #3 https://github.com/Ptival/PeaCoq/issues/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Ptival/PeaCoq/issues/3#event-225732208.

## 

Sent from a mobile device.
