### ISSUE TITLE
Typescript fails to build on latest version of typescript compiler

### ISSUE THREAD

**Issue by hugovincent** [Ptival/PeaCoq#35]
It seems that perhaps some recent changes upstream in the Typescript compiler cause the build to fail:

```
editor/edit.ts(68,28): error TS2304: Cannot find name 'PeaCoqContext'.
editor/edit.ts(82,25): error TS2304: Cannot find name 'PeaCoqContext'.
editor/edit.ts(98,30): error TS2304: Cannot find name 'PeaCoqContext'.
editor/editor.d.ts(121,25): error TS2304: Cannot find name 'PeaCoqContext'.
editor/editor.ts(23,32): error TS2304: Cannot find name 'PeaCoqContext'.
editor/editor.ts(26,39): error TS2339: Property 'ppgoal' does not exist on type '{}'.
peacoq/peacoq.ts(1,28): error TS2304: Cannot find name 'PeaCoqContext'.
prooftree/goalnode.ts(20,21): error TS2304: Cannot find name 'PeaCoqContext'.
prooftree/prooftree.d.ts(64,12): error TS2304: Cannot find name 'PeaCoqContext'.
html-printers.ts(18,33): error TS2304: Cannot find name 'PeaCoqHyp'.
html-printers.ts(29,37): error TS2304: Cannot find name 'PeaCoqHyp'.
peacoq-goal.ts(12,36): error TS2304: Cannot find name 'IPeaCoqGoal'.
peacoq-goal.ts(16,19): error TS2304: Cannot find name 'PeaCoqHyp'.
setup.ts(405,36): error TS2304: Cannot find name 'PeaCoqContext'.
```

In addition, [`web/package.json`](https://github.com/Ptival/PeaCoq/blob/master/web/package.json) doesn't peg versions (same for bower), so this is likely to keep happening in the future, and it's not easy to see which versions of npm components the project maintainers are using. I'd recommend pegging versions in `package.json` (at least to minor or patch versions) and periodically updating them, rather than using `*`.

**Comment by Ptival** [comment]
Yeah I know this happens and how to fix it, but the fix makes me think I'm doing something wrong.

It seems I need to add a <reference path> because the .d.ts does not get found by tsc. But adding it into any of the files works, which is weird. I guess I'll put it in the main file for now, but I feel like there should be a way to have tsc find them...

Re `package.json`, I'll have to fix those numbers yeah, sorry for the inconvenience, I will try to do it this afternoon! :-)

Thanks for the issue! How do you know about PeaCoq?

**Comment by Ptival** [comment]
Ah I understand now. `tsc` will ignore definition files if they have the same name as a non-definition file (I guess it assumes it's the interface file for that file).

I moved the definition files to a separate location so that `tsc` picks up on them.

**Comment by Ptival** [comment]
Fixed in 7455fb8.

**Comment by hugovincent** [comment]
Brilliant, thanks, that fixes that problem. I now get a runtime error (in the browser console) when running:

```
Uncaught (in promise) ReferenceError: GType is not defined
    at eval (eval at walkJSON (http://localhost:4323/js/peacoq-js-of-ts/peacoq/json.js:7:46), <anonymous>:1:1)
    at walkJSON (http://localhost:4323/js/peacoq-js-of-ts/peacoq/json.js:7:36)
    at arrayMap (http://localhost:4323/bower_components/lodash/lodash.js:619:23)
    at Function.map (http://localhost:4323/bower_components/lodash/lodash.js:8712:14)
    at interceptor (http://localhost:4323/bower_components/lodash/lodash.js:16034:35)
    at thru (http://localhost:4323/bower_components/lodash/lodash.js:7934:14)
    at http://localhost:4323/bower_components/lodash/lodash.js:3848:28
    at arrayReduce (http://localhost:4323/bower_components/lodash/lodash.js:663:21)
    at baseWrapperValue (http://localhost:4323/bower_components/lodash/lodash.js:3847:14)
    at LazyWrapper.lazyValue [as value] (http://localhost:4323/bower_components/lodash/lodash.js:1645:16)
```

I also get no output. Is that expected at this stage in the project? It looks (from the server console) like it's correctly invoking Coq and running code, but the output panes are all blank. (Do you want me to open a new issue for this?)

**Comment by Ptival** [comment]
Thanks! Fixed that one with fb6b2f6.

**Comment by hugovincent** [comment]
Perfect, many thanks. Still no output, but at least no errors now. I'll try to diagnose what's going on and if necessary open a new issue tomorrow.

**Comment by Ptival** [comment]
What code are you trying to run?
