### ISSUE TITLE
Highlighting + typing doesn't replace the highlighted region

### ISSUE THREAD

**Issue by darzu** [Ptival/PeaCoq#4]
If I highlight a region then type e.g. "a", an "a" gets inserted at the cursor position but the highlight region isn't deleted like I would expect.

**Comment by Ptival** [comment]
So, I have a fix for this, however it has the drawback that the action is not undoable.

I am working on a new version of the editor where most things would work better and be undoable, in the meantime I will probably push that less satisfactory patch tonight.

Keeping this open as a reminder! :)

**Comment by darzu** [comment]
Got it. Thanks for the hard work!

**Comment by darzu** [comment]
Actually, on second thought, I'd probably opt for keeping things as-is until undo would be available because I think having undo is probably more important and safer than having the highlight deletion which is really just a convenience.

But either way, it's not a big difference.

**Comment by Ptival** [comment]
Fixed by b69f9193d98d4c68d90cee857e5fdf6df176478c

**Comment by ztatlock** [comment]
Is undo supported?

On Tuesday, January 27, 2015, Valentin Robert notifications@github.com
wrote:

> Fixed by b69f919
> https://github.com/Ptival/PeaCoq/commit/b69f9193d98d4c68d90cee857e5fdf6df176478c
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Ptival/PeaCoq/issues/4#issuecomment-71749104.

## 

Sent from a mobile device.

**Comment by Ptival** [comment]
Undo is only supported for actions that do not need to be emulated to function correctly.

In particular, Undo is not supported for:
- cut and paste
- inputing a newline character (Enter)
- hitting Backspace

**Comment by ztatlock** [comment]
Lol, can't undo Backspace.

Is this fundamental?

**Comment by Ptival** [comment]
Sorry, actually it's only Backspace for the first character after the locked region.

It's fundamental because I emulate some interactions where the default browser implementation would mess things up.
