### ISSUE TITLE
[low-pri] More eager syntax highlighting

### ISSUE THREAD

**Issue by darzu** [Ptival/PeaCoq#6]
A nice-to-have, not need-to-have. But it'd be nice if the syntax highlighter kicked in a bit more eagerly, or at least if there was a keyboard shortcut to invoke it.

**Comment by Ptival** [comment]
Right now this is complicated by the fact that it is complex to keep track of the caret position when syntax highlighting is done.

In the current setup, the full text is passed to highlight.js which returns a highlighted DOM. I do not know yet how to map the caret position in the original text to a position in the resulting DOM.

**Comment by ztatlock** [comment]
Could this help?

https://developer.mozilla.org/en-US/docs/Web/API/document.caretPositionFromPoint

**Comment by ztatlock** [comment]
Here's one way to do it maybe?

http://stackoverflow.com/questions/8035010/contenteditable-true-creating-a-syntax-highlighted-input-form

**Comment by Ptival** [comment]
@ztatlock Damn, that's cool, I'm already using Rangy too, it should be easy now! Let's try!

**Comment by Ptival** [comment]
Fixed in branch codemirror with a better syntax highlighter too!
