### ISSUE TITLE
Syntax Error: Lexer: Unsupported Unicode character (0x200b)

### ISSUE THREAD

**Issue by emackay** [Ptival/PeaCoq#7]
It seems that either when loading or saving a PeaCoq file, it might be inserting these Unicode characters. I believe this is a zero-width space or something. Since these characters aren't visible, it's not easy to find and delete them

**Comment by Ptival** [comment]
Hi,

Indeed PeaCoq uses this invisible character as a way to trick the browser into doing the right things. Could you please indicate on which machine you have had this problem?

I pushed changes that should get rid of this character upon reloading the file. If you refresh your browser, you should hopefully be able to load this file and continue working.

**Comment by emackay** [comment]
I am on attu. After refreshing my browser, it seems to work perfectly now. Thanks!

---

Eric W Mackay
University of Washington
PhD Student, Computer Science and Engineering
CSE 410
