### ISSUE TITLE
Allow saving with ctrl-s

### ISSUE THREAD

**Issue by darzu** [Ptival/PeaCoq#9]

**Comment by ztatlock** [comment]
+1

**Comment by Ptival** [comment]
:earth_africa:, :dash:, and :fire:, where is the :heart: for :droplet:?

**Comment by ztatlock** [comment]
https://www.youtube.com/watch?v=xycnv87N_BU

**Comment by Ptival** [comment]
Fixed by 198cc67 with Ctrl-Alt-(L/S)
